services:
  comparator.repository:
    class: Vain\Comparator\Repository\ComparatorRepository
  comparator.basic:
    class: Vain\Comparator\Basic\BasicComparator
    tags:
      - {name: comparator}
  comparator.string:
    class: Vain\Comparator\String\StringComparator
    tags:
      - {name: comparator}
  comparator.time:
    class: Vain\Comparator\Time\TimeComparator
    tags:
      - {name: comparator}
  comparator.value:
    class: Vain\Comparator\Value\ValueComparator
    tags:
      - {name: comparator}