services:
    comparator.repository:
        class: Vain\Comparator\Repository\ComparatorRepository
        calls:
          - [addComparator, ['int', '@comparator.basic']]
          - [addComparator, ['float', '@comparator.int']]
          - [addComparator, ['double', '@comparator.int']]
          - [addComparator, ['string', '@comparator.string']]
          - [addComparator, ['value', @comparator.value']]
    comparator.basic:
        class: Vain\Comparator\Basic\BasicComparator
    comparator.string:
        class: Vain\Comparator\String\StringComparator
    comparator.value:
        class: Vain\Comparator\Value\ValueComparator