services:
    comparator.repository:
        class: Vain\Comparator\Repository\ComparatorRepository
        calls:
          - [addComparator, ['@comparator.basic']]
          - [addComparator, ['@comparator.string']]
          - [addComparator, ['@comparator.value']]
    comparator.basic:
        class: Vain\Comparator\Basic\BasicComparator
    comparator.string:
        class: Vain\Comparator\String\StringComparator
    comparator.value:
        class: Vain\Comparator\Value\ValueComparator