services:
    comparator.factory:
        class: Vain\Comparator\Factory\ComparatorFactory
    comparator.repository:
        class: Vain\Comparator\Repository\ComparatorRepository
        arguments: ['@comparator.factory']